### ISSUE TITLE
3. *Effects - Effect creation system. 

### ISSUE THREAD

**Issue by Risorm** [Peruvian-lily/OOP-Teamwork#10]
```
- Holds single Stat //Subject to change
- Implements ITimeout(); //Lasts X turns.
- Has method Target(Npc target) //Target of effect
    ex. Healing(); //On event changes stats of target 
```

**Comment by Emil-Petrov** [comment]
Added abstract class Effects (Effect name is reserved by monogame).
Effects(Stat, Target, duration = optional)
Stat - holds the stat it effects
Target - target it affects
Duration - defaults to 1

Has abstract method Apply() for use with target.
