### ISSUE TITLE
4. Inventory

### ISSUE THREAD

**Issue by Risorm** [Peruvian-lily/OOP-Teamwork#11]
```
- Holds list of Items.
- AddItem() and RemoveItem() methods.
    -Can add Equip() at a later date.
- Has capacity. //X items Diablo stype or Y weight fallout style. If second add Weight property to Item.
```

**Comment by Emil-Petrov** [comment]
Added Inventory class with validation for size. Holds list of items and has methods for Adding, Removing items and increasing capacity.

Inventory(int Capacity)
Capacity - sets the capacity of inventory. Must be higher than 5 //Magic number
Add(Item item) - adds item to inventory.
Remove(Item item) - removes item from inventory.
Expand(int size) - increases capacity by size.
Content - Property, returns list of items.

Capt'n Obvious out!
