### ISSUE TITLE
		1.1.1. Player 

### ISSUE THREAD

**Issue by Risorm** [Peruvian-lily/OOP-Teamwork#18]
```
         - Implements IMove(), IFight(),IPlayer()
```

**Comment by Emil-Petrov** [comment]
Added Player class. Extends NPC, Implements IPlayer.
Player(id, name, health, attack, defense, inventory, others)
id - inherited.
name - inherited.
health - holds integer value for health
attack - holds integer value for attack
defense - holds integer value for defense
inventory - holds integer value for inventory size
other - holds a list of extra stats (Optional)

Attack(target) - Deals damage to target based on target defense and player offense.
Move() - not yet implemented.
PickUp(item) - picks up item. //Adds to inventory if item, applies bonuses if bonus etc.

**Comment by Emil-Petrov** [comment]
Move() needs to be implemented.
