### ISSUE TITLE
		1.1.2. Enemy	

### ISSUE THREAD

**Issue by Risorm** [Peruvian-lily/OOP-Teamwork#19]
```
        - Inherits NPC 
        - Implements IRoam(), IFight(), IEnemy()
```

**Comment by Emil-Petrov** [comment]
Added Enemy class
Enemy(id, name, health, attack, defense, stats)
id, name, health - inherited.
attack, defense - attack and defense stats of enemy used for fighting calculations.
stats - optional, other stats.
