### ISSUE TITLE
1.2.1. Item //Permanent pick up goes in inventory. 

### ISSUE THREAD

**Issue by Risorm** [Peruvian-lily/OOP-Teamwork#5]
```
        - Can be made abstracts if we want a set number of items. Or keep like this for random generation.
        - Inherits PickUp. 
        - Implements IItem();
        - Contains amount of uses.
```

**Comment by Emil-Petrov** [comment]
Added base class Item with validation. Contains List of stats and effects. Uses not added
Item(id,name,stats,effects = null)
id - inherited.
name - inherited.
stats - contains list of stats. Must contain more than 2 objects of type stat.
effects - optional. Item can contain a list of effects.
